[tools]
bat = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
neovim = "0.10.2"
ripgrep = "latest"
ruby = "3.2"
shellcheck = "latest"
starship = "1.21.1"
xcodes = "1.5.0"
zoxide = "latest"
"cargo:diskonaut" = "latest"
"cargo:lowfi" = "latest"
"cargo:git-trim" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/charmbracelet/gum" = "latest"
"go:github.com/icholy/git-get" = "latest"
"go:github.com/git-town/git-town/v16" = "16.5.0"
"go:github.com/tomnomnom/gron" = "latest"
"go:github.com/charmbracelet/mods" = "latest"

[settings]
experimental = true
