[tools]
flutter = "latest"
go = "latest"
xcodes = "1.5.0"
neovim = "stable"
ruby = "3.2"
jq = "latest"
fd = "latest"
"cargo:difftastic" = "latest"
"cargo:diskonaut" = "latest"
"cargo:lowfi" = "latest"
"cargo:git-trim" = "latest"
"cargo:ripgrep" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/charmbracelet/gum" = "latest"
"go:github.com/icholy/git-get" = "latest"
"go:github.com/git-town/git-town/v16" = "16.4.1"
"go:github.com/charmbracelet/freeze" = "latest"
"go:github.com/tomnomnom/gron" = "latest"
"go:github.com/coder/aicommit/cmd/aicommit" = "latest"
"go:github.com/charmbracelet/mods" = "latest"

[settings]
experimental = true
