[tools]
flutter = "latest"
go = "latest"
xcodes = "1.5.0"
neovim = "stable"
ruby = "3.2"
"cargo:difftastic" = "latest"
"cargo:diskonaut" = "latest"
"cargo:lowfi" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/charmbracelet/gum" = "latest"
"go:github.com/icholy/git-get" = "latest"
"go:github.com/git-town/git-town/v16" = "16.4.1"
"cargo:git-trim" = "latest"

[settings]
experimental = true
