[tools]
"cargo:diskonaut" = "latest"
"cargo:difftastic" = "latest"
"cargo:jj-cli" = "latest"
"go:github.com/icholy/git-get" = "latest"
"spm:alphatroya/stylus-telegram-bot" = "v1.1"
go = "latest"
jjui = "latest"
lua-language-server = "latest"
neovim = "latest"
rust = "latest"
stylua = "latest"
"cargo:jj-starship" = "latest"
tree-sitter = "latest"

[settings]
experimental = true
