#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do
  before_all do
  end

  desc 'Bootstrap project for the developing'
  lane :bootstrap do
  end

  desc 'Invoke all tests'
  lane :test do
  end

  desc 'Deploy a new beta build'
  lane :beta do
  end

  desc 'Deploy a release build'
  lane :release do
  end

  after_all do |_lane|
    clean_build_artifacts
  end

  error do |_lane, _exception|
    clean_build_artifacts
  end
end
