[user]
name = "Alexey Korolev"
email = "{{ (keepassxc "primary email").UserName }}"

[[--scope]]
--when.repositories = ["~/src/gitlab.handh.ru", "~/src/gitea.handh.ru:222", "~/src/gitea.handh.ru"]
[--scope.user]
email = "{{ (keepassxc "hh email").UserName }}"

[ui]
diff.tool = ["difft", "--color=always", "$left", "$right"]
default-command = "log"
