[user]
name = "Alexey Korolev"
email = "alphatroya@gmail.com"

[[--scope]]
--when.repositories = ["~/src/gitlab.handh.ru", "~/src/gitea.handh.ru:222", "~/src/gitea.handh.ru"]
[--scope.user]
email = "a.korolev@headsandhands.ru"

[ui]
diff.tool = ["difft", "--color=always", "$left", "$right"]
