# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - triggers: ["shrug_", "ыркгп_"]
    replace: '¯\_(ツ)_/¯'

  - triggers: [qc_, йс_]
    replace: "**{{time}}**"
    vars:
      - name: time
        type: shell
        params:
          cmd: "date +\"%H:%M\""

  - triggers: [qcc_, йсс_]
    replace: "**{{time}}** [[{{date}}]] "
    vars:
      - name: time
        type: shell
        params:
          cmd: "date +\"%H:%M\""
      - name: date
        type: script
        params:
          args:
            - bash
            - '-c'
            - |
                d=$(date +%-d)

                case $d in
                  1|21|31) suf="st" ;;
                  2|22)    suf="nd" ;;
                  3|23)    suf="rd" ;;
                  *)       suf="th" ;;
                esac

                printf '%s %d%s, %s\n' "$(date +%b)" "$d" "$suf" "$(date +%Y)"

  - trigger: "cmark_"
    replace: '✅'

  - trigger: "tada_"
    replace: '🎉'

  - trigger: "руб_"
    replace: '₽'
