#!/usr/bin/env bash

# Russian typos
alias агсл="fuck"
alias учше="exit"

# Alternatives to standard tools
alias vim="nvim"
alias ls="exa"
alias cat="bat"
alias gpp="gp &"

# git aliases
alias gloga="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gfap="git fetch --all --prune"
alias gcS=gcs

# gh aliases
alias ghp="gh pr"
alias ghpc="gh pr checks"
alias ghpco="gh pr checkout"
alias ghpa="gh pr review -a"
alias ghpd="gh pr diff"

alias rstatus='git log --since=8:00am --author="Alexey Korolev" | grep -Eo "Close #[0-9]+" | sed "s/Close #//"  | xargs echo "/fhm" | tr -d "\\n" | pbcopy'

# kubernetes
alias k=kubectl

# Fill Redmine hours aliases
alias fillredmine='z stun && vim work.csv && git commit --all -m "Update $(date -u +"%Y-%m-%d")" && git push && cd -'
alias fillredmineloc='z stun && vim work.csv && docker run -e REDMINE_API_KEY -e REDMINE_HOST -v $(pwd):/home/appuser/data fiction --csv data/work.csv && cd -'

