#!/usr/bin/env bash

# Difftastic
alias gdiff="GIT_EXTERNAL_DIFF=difft git diff"
alias gshow="GIT_EXTERNAL_DIFF=difft git show --ext-diff"

# Russian typos
alias учше="exit"

# Alternatives to standard tools
alias vim="nvim"
alias cat="bat"

# git aliases
alias gloga="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gfap="git fetch --all"
alias gsy="git town sync"
alias gha="git town hack"

# Fill Redmine hours aliases
log_hours() {
    if [[ ! -f work.csv ]]; then
        pushd /Users/alphatroya/src/github.com/alphatroya/stunning-enigma || exit
        should_popd=true
    else
        should_popd=false
    fi

    git pull
    if [[ -n "$1" ]]; then
        file="work.csv"
        line=$(printf "%s,,Работа" "$1")
        if [ -s "$file" ]; then
            echo "$line" >> "$file"
        else
            echo "$line" > "$file"
        fi
    else
        vim work.csv
    fi
    if [[ $(git status --porcelain) ]]; then
        git commit --all -m "Update $(date -u +"%Y-%m-%d")" && git push
    else
        echo "Nothing to commit, exit"
    fi

    if [[ $should_popd == true ]]; then
        popd || exit
    fi
}

alias -s git="git get"
