#!/usr/bin/env bash

# Russian typos
alias агсл="fuck"
alias учше="exit"

# Alternatives to standard tools
alias vim="nvim"
alias ls="exa"
alias cat="bat"
alias gpp="gp &"

# git aliases
alias gloga="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gfap="git fetch --all --prune"
alias gcS=gcs

# gh aliases
alias ghp="gh pr"
alias ghpc="gh pr checks"
alias ghpco="gh pr checkout"
alias ghpa="gh pr review -a"
alias ghpd="gh pr diff"

alias rstatus='git log --since=8:00am --author="Alexey Korolev" | grep -Eo "Close #[0-9]+" | sed "s/Close #//"  | xargs echo "/fhm" | tr -d "\\n" | pbcopy'

# kubernetes
alias k=kubectl

# Fill Redmine hours aliases
alias fillredmine='z stun && git pull && vim work.csv && git commit --all -m "Update $(date -u +"%Y-%m-%d")" && git push && cd -'
alias fillredmineloc='z stun && git pull && vim work.csv && docker run -e REDMINE_API_KEY -e REDMINE_HOST -v $(pwd):/home/appuser/data fiction --csv data/work.csv && cd -'

# measure curl timing (https://susam.in/maze/timing-with-curl.html)
alias curlt='curl -L -w "time_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_appconnect: %{time_appconnect}\ntime_pretransfer: %{time_pretransfer}\ntime_redirect: %{time_redirect}\ntime_starttransfer: %{time_starttransfer}\ntime_total: %{time_total}\n"'

# view files tree
alias lt1='exa --tree -L1'
alias lt2='exa --tree -L2'
alias lt3='exa --tree -L3'
