#!/usr/bin/env bash

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-completions

antigen bundle git
antigen bundle editor
antigen bundle history
antigen bundle prompt
antigen bundle utility
antigen bundle completion

antigen bundle Aloxaf/fzf-tab
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply
