#!/usr/bin/env bash

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-completions

antigen bundle git
antigen bundle editor
antigen bundle history
antigen bundle prompt
antigen bundle utility
antigen bundle completion
antigen bundle command-not-found

antigen bundle Aloxaf/fzf-tab
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme spaceship-prompt/spaceship-prompt

antigen apply
