#!/usr/bin/env bash

export EDITOR="nvim"
export VISUAL="nvim"
export LANG="en_US.UTF-8"

# Initialize ruby
eval "$(rbenv init - zsh)"

# Configure thefuck tool
eval $(thefuck --alias)
fuck-command-line() {
    local FUCK="$(THEFUCK_REQUIRE_CONFIRMATION=0 thefuck $(fc -ln -1 | tail -n 1) 2> /dev/null)"
    [[ -z $FUCK ]] && echo -n -e "\a" && return
    BUFFER=$FUCK
    zle end-of-line
}
zle -N fuck-command-line

# Configure zoxide
eval "$(zoxide init zsh)"

# Configure direnv
eval "$(direnv hook zsh)"

# Configure prompt
eval "$(starship init zsh)"

# Configure fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

