#!/usr/bin/env bash

export EDITOR="nvim"
export VISUAL="nvim"
export LANG="en_US.UTF-8"

# Initialize ruby
eval "$(rbenv init - zsh)"

# Configure zoxide
eval "$(zoxide init zsh --cmd cd)"

# Configure prompt
eval "$(starship init zsh)"

# Configure fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

