#!/usr/bin/env bash

export EDITOR="nvim"
export VISUAL="nvim"
export LANG="en_US.UTF-8"

# Initialize ruby
eval "$(rbenv init - zsh)"

# Configure zoxide
eval "$(zoxide init zsh --cmd cd)"

# Configure prompt
eval "$(starship init zsh)"

# Configure fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add brew completion folder to fpath
fpath=(~/.zsh/completion $fpath)
if type brew &>/dev/null; then
    fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fi
autoload -U compinit
compinit

