#!/usr/bin/env bash

function create-feature() {

    local jq_template branch_name

    jq_template='"'\
'\(.id). \(.project.name) \(.subject)'\
'\t'\
'Reporter: \(.author.name)\n'\
'Created: \(.created_on)\n'\
'Updated: \(.updated_on)\n\n'\
'\(.description)'\
'"'

    branch_name=$(
        curl \
            --get \
            -H "X-Redmine-API-Key":"$REDMINE_API_KEY" \
            --silent \
            --compressed \
            "$REDMINE_HOST/issues.json?assigned_to_id=me&limit=200" |
            jq ".issues[] | $jq_template" |
            sed -e 's/"\(.*\)"/\1/' -e 's/\\t/\t/' |
            fzf \
                --with-nth=1 \
                --delimiter='\t' \
                --preview='echo -e {2}' \
                --preview-window=top:wrap |
            cut -f1 |
            sed -e 's/\. /\t/' -e 's/[^0-9\t]//g'
    )

    if [ -n "$branch_name" ]; then
        echo $branch_name
    fi
}
